"""Generate database/seed_data.sql from the canonical seed data + scoring.

Run:  python gen_seed_sql.py   (from backend/, venv active)
Keeps the pure-SQL seed in sync with app/seed.py so it can be applied with psql.
"""
import json

from app.scoring import score_email
from app.security import hash_password
from app.seed import DAYS_AGO, SAMPLE_EMAILS, USERS


def q(s: str) -> str:
    """SQL-escape a string literal."""
    if s is None:
        return "NULL"
    return "'" + str(s).replace("'", "''") + "'"


lines = [
    "-- PhishGuard pure-SQL seed data (PostgreSQL).",
    "-- AUTO-GENERATED by backend/gen_seed_sql.py -- do not edit by hand.",
    "-- Apply after schema.sql:   psql -d phishguard_db -f database/seed_data.sql",
    "-- Password hashes are real bcrypt hashes of the documented demo passwords.",
    "-- NO real email data is used; every message is synthetic.",
    "",
    "TRUNCATE audit_logs, staff_release_requests, analyst_reviews, email_records, users RESTART IDENTITY CASCADE;",
    "",
    "-- Users -----------------------------------------------------------------",
]

for u in USERS:
    h = hash_password(u["password"])
    lines.append(
        "INSERT INTO users (email, full_name, hashed_password, role, is_active) VALUES "
        f"({q(u['email'])}, {q(u['full_name'])}, {q(h)}, {q(u['role'])}, TRUE);"
    )

lines += ["", "-- Email records ----------------------------------------------------------"]
scored = []
for i, (sender, name, rcpt, subj, body) in enumerate(SAMPLE_EMAILS):
    r = score_email(sender, subj, body, name)
    scored.append(r)
    status = "quarantined" if r.level in ("high", "critical") else "inbox"
    mid = f"<sample-{i + 1}@phishguard.local>"
    lines.append(
        "INSERT INTO email_records (message_id, sender, sender_name, recipient, subject, body, "
        "status, risk_score, risk_level, score_reasons, auth_spf, auth_dkim, auth_dmarc, ai_generated, "
        "received_at) VALUES (\n"
        f"  {q(mid)}, {q(sender)}, {q(name)}, {q(rcpt)}, {q(subj)}, {q(body)},\n"
        f"  {q(status)}, {r.score}, {q(r.level)}, {q(json.dumps(r.reasons))}, "
        f"{q(r.spf)}, {q(r.dkim)}, {q(r.dmarc)}, {str(r.ai_generated).upper()}, "
        f"(CURRENT_DATE - INTERVAL '{DAYS_AGO[i]} days' + INTERVAL '12 hours'));"
    )

# Worst email -> confirmed phishing review + audit
worst_idx = max(range(len(scored)), key=lambda i: scored[i].score)
worst_subj = SAMPLE_EMAILS[worst_idx][3]
lines += [
    "",
    "-- One confirmed-phishing analyst review on the highest-risk email ---------",
    "INSERT INTO analyst_reviews (email_id, analyst_id, action, verdict, feedback) "
    "SELECT e.id, u.id, 'confirm_phishing', 'phishing', "
    "'Classic credential-harvesting page, IP-based link.' "
    f"FROM email_records e, users u WHERE e.message_id = {q(f'<sample-{worst_idx + 1}@phishguard.local>')} "
    "AND u.email = 'analyst@phishguard.local';",
    f"UPDATE email_records SET status = 'confirmed_phishing' WHERE message_id = {q(f'<sample-{worst_idx + 1}@phishguard.local>')};",
    "INSERT INTO audit_logs (user_id, actor_email, action, entity_type, entity_id, details, ip_address) "
    "SELECT u.id, u.email, 'confirm_phishing', 'email', e.id, "
    f"'confirm_phishing on email ' || {q(worst_subj)}, '127.0.0.1' "
    f"FROM email_records e, users u WHERE e.message_id = {q(f'<sample-{worst_idx + 1}@phishguard.local>')} "
    "AND u.email = 'analyst@phishguard.local';",
]

# A pending staff release request on a quarantined email for staff@
first_quar = next(
    (i for i, (s, n, rcpt, subj, b) in enumerate(SAMPLE_EMAILS)
     if rcpt == "staff@phishguard.local" and scored[i].level in ("high", "critical") and i != worst_idx),
    None,
)
if first_quar is not None:
    quar_mid = f"<sample-{first_quar + 1}@phishguard.local>"
    quar_subj = SAMPLE_EMAILS[first_quar][3]
    lines += [
        "",
        "-- One pending staff release request --------------------------------------",
        "INSERT INTO staff_release_requests (email_id, requested_by, reason, status) "
        "SELECT e.id, u.id, "
        "'I was expecting this message from a vendor -- please review for release.', 'pending' "
        f"FROM email_records e, users u WHERE e.message_id = {q(quar_mid)} "
        "AND u.email = 'staff@phishguard.local';",
        "INSERT INTO audit_logs (user_id, actor_email, action, entity_type, entity_id, details, ip_address) "
        "SELECT u.id, u.email, 'release_request_created', 'release_request', r.id, "
        f"'Requested release of email ' || {q(quar_subj)}, '127.0.0.1' "
        "FROM staff_release_requests r, users u WHERE u.email = 'staff@phishguard.local' "
        "ORDER BY r.id DESC LIMIT 1;",
    ]

lines.append("")
with open("../database/seed_data.sql", "w", encoding="utf-8") as f:
    f.write("\n".join(lines))
print(f"Wrote database/seed_data.sql ({len(lines)} lines)")
