"""Write one named section into screenshots/INDEX.md without disturbing the others.

capture_postgres_evidence.py and capture_ci_evidence.py each own a section of the
index. The first version of both simply truncated the file at their own heading and
appended, which meant whichever ran first lost its section to whichever ran second.
This replaces a section in place — bounded by its heading and the next heading —
and appends it only if it is not there yet, so the two scripts can run in any order,
any number of times.
"""
from __future__ import annotations

import re
from pathlib import Path


def write_section(index: Path, heading: str, lines: list[str]) -> bool:
    """Insert or replace ``heading`` and its body in ``index``.

    ``heading`` must include its own leading ``##``. Returns False if the file does
    not exist, since the index is generated by capture_screenshots.py.
    """
    if not index.exists():
        return False

    body = index.read_text(encoding="utf-8")
    section = f"\n{heading}\n\n" + "\n".join(lines).rstrip() + "\n"

    pattern = re.compile(
        rf"\n{re.escape(heading)}\n.*?(?=\n## |\Z)", re.S)
    if pattern.search(body):
        # The lookahead leaves the newline before the next heading unconsumed, so
        # the replacement must end with one of its own to keep a blank line there.
        body = pattern.sub(section.rstrip("\n") + "\n", body)
    else:
        body = body.rstrip("\n") + "\n" + section

    index.write_text(body.rstrip("\n") + "\n", encoding="utf-8")
    return True
