"""Remove whole parts from a saved OOXML package, relationships included.

python-docx and python-pptx can edit a document's content but not easily drop parts
Word or PowerPoint attached on the side. Two of those matter for a submitted file:

  customXml/*            A data store Word carries over from whatever template or
                         earlier document the file descends from. It is invisible on
                         the page and can retain fields from a previous author.
  docProps/thumbnail.*   A rendered preview of the first page, regenerated by Word.
                         Harmless in itself, but it is document metadata that nothing
                         in the report needs.

Dropping a part without dropping the relationship that points at it produces a file
Word reports as corrupt, so both are removed together.

Usage:
    python evidence/strip_package_parts.py <file.docx|file.pptx> [pattern ...]
"""
from __future__ import annotations

import re
import shutil
import sys
import zipfile
from pathlib import Path

DEFAULT_PATTERNS = ("customXml/", "docProps/thumbnail")


def strip(path: Path, patterns: tuple[str, ...] = DEFAULT_PATTERNS) -> list[str]:
    """Rewrite ``path`` in place without the matching parts. Returns what went."""
    src = zipfile.ZipFile(path)
    doomed = [n for n in src.namelist() if any(p in n for p in patterns)]
    if not doomed:
        src.close()
        return []

    # Relationship ids pointing at a doomed target, so the .rels files can be fixed.
    targets = {n.split("/")[-1] for n in doomed} | {n for n in doomed}

    tmp = path.with_suffix(path.suffix + ".tmp")
    with zipfile.ZipFile(tmp, "w", zipfile.ZIP_DEFLATED) as out:
        for item in src.infolist():
            if item.filename in doomed:
                continue
            data = src.read(item.filename)

            if item.filename.endswith(".rels"):
                text = data.decode("utf-8")
                # Drop any Relationship whose Target names a removed part.
                def keep(m: re.Match) -> str:
                    tag = m.group(0)
                    tm = re.search(r'Target="([^"]+)"', tag)
                    if tm:
                        tail = tm.group(1).split("/")[-1]
                        if tail in targets or any(p in tm.group(1) for p in patterns):
                            return ""
                    return tag
                text = re.sub(r"<Relationship\b[^>]*/>", keep, text)
                data = text.encode("utf-8")

            elif item.filename == "[Content_Types].xml":
                text = data.decode("utf-8")
                for n in doomed:
                    text = text.replace(f'<Override PartName="/{n}"', "<!--removed ")
                text = re.sub(r"<!--removed [^>]*>", "", text)
                data = text.encode("utf-8")

            out.writestr(item, data)
    src.close()
    shutil.move(str(tmp), str(path))
    return doomed


def main() -> int:
    if len(sys.argv) < 2:
        raise SystemExit(__doc__)
    path = Path(sys.argv[1])
    patterns = tuple(sys.argv[2:]) or DEFAULT_PATTERNS
    gone = strip(path, patterns)
    print(f"{path.name}: removed {len(gone)} part(s)")
    for n in gone:
        print(f"  {n}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
